### ISSUE TITLE
UI tweaking tracking issue

### ISSUE THREAD

**Issue by adilanchian** [PixelogicDev/SimpleAlerts#18]
This will be a dynamic list for tracking UI changes as we go.

### EventListComponent
- [x] Empty state for component
- [x] Did read event
- [x] Remove event list X action
- [x] Edit event list title
- [x] Tool tips
- [x] All buttons should have a hover and pointer cursor
- [x] Fix placement of containers
- [x] Fix input of title when creating new list 
- [x] Add header
- [x] Add place holder for adding new list

**Comment by adilanchian** [comment]
I believe this is good to go! Closing this out and moving onto the next 👍
